### ISSUE TITLE
Styling for plugin help pages

### ISSUE THREAD

**Issue by ndesimone** [Dan-in-CA/SIP#115]
Not really an issue, but at some point some thought should be put into styling the plug-in help pages.  You can see what I mean by clicking the help button in the system update plug in.

I see a couple of options:

- Help appears in the main application window (not my first choice)
- Have the help button open a new "help" window and apply an appropriate styling

**Comment by Dan-in-CA** [comment]
The help button does open a new window. this is to allow for easily switching between help and the app pages.

Agreed that a style sheet for the help pages would be a big improvement. I'll see if the style sheet for the UI will work.

**Comment by Dan-in-CA** [comment]
added the following line to the plugin docs pages:
    <link href="../../themes/basic/base.css" rel="stylesheet" type="text/css"/>

It is a start. If anyone wants to contribute an improved style sheet for the docs pages it would be welcome.
