### ISSUE TITLE
No sip.sh in repo

### ISSUE THREAD

**Issue by ndesimone** [Dan-in-CA/SIP#117]
Hey Dan, I know you're in the process of renaming so this is more of a to-do.  We'll need a sip.sh and phase out ospi.sh.  My suggestion:

- Move ospi.sh to sip.sh
- Create a new ospi.sh that simply calls sip.sh (that way people's existing stuff doesn't break)
- Phase out ospi.sh over time

Hope this helps,
Nick

**Comment by Dan-in-CA** [comment]
Thanks for the suggestions.

I made a modified sip.sh that points to the SIP directory. That's where any new clones will be.
There is also a new ospi.py file that is a symlink pointing to sip.py this should keep any existing installations working from the OSPi dir. The old ospi file in /etc/init.d/ will still work but any new set ups that point to the SIP dir will work also.
