### ISSUE TITLE
Water level adjustment not working

### ISSUE THREAD

**Issue by begeles2000** [Dan-in-CA/SIP#123]
I updated recently to version  3.0.12  and now neither automatic water level adjustment or manual water level adjustments are working. Is this only happening to me?

**Comment by Dan-in-CA** [comment]
I just pushed an update that will now show the total water level adjustments including plugins.
I am not seeing the problem you describe. Try updating the software again and if you are still seeing the problem let me know. 

There is now a brand new forum for this project at:
http://nosack.com/sipforum/index.php

If you could post any problem reports there it would be likely to help others as well.

Thanks.

Dan

**Comment by begeles2000** [comment]
my bad, the problem was that the water time adjustment is not shown on the schelude for the future, but it is applied when the program is run.
