### ISSUE TITLE
/vs stations page will not load if non CA weather based water level plugin is enabled

### ISSUE THREAD

**Issue by gdgeist** [Dan-in-CA/SIP#126]
/vs stations page will not load if non CA weather based water level plugin is enabled.  disabling permits /vs page to load.

**Comment by Dan-in-CA** [comment]
What version of the software are you using?
I am not seeing the problem with version 3.1.16.

**Comment by gdgeist** [comment]
found the problem - the change from ospi.py to sip.py didnt automatically update the startup script for init.d so ospi.py has been loading
