### ISSUE TITLE
^Ms in files

### ISSUE THREAD

**Issue by ndesimone** [Dan-in-CA/SIP#134]
Just checking if anyone else is seeing ctrl-Ms in some of the files (e.g. gv.py).  If so, we probably need to dos2unix some of these files.

**Comment by natejgreene** [comment]
yep I have seen them.

**Comment by Qry3vavna** [comment]
if you don't have dos2unix installed and can't get to the internet, then you can create a simple Bash function calling sed to substitute '\r' with nothing.
dos2unix() {
  sed -i 's/\r//g' $*
}

**Comment by Dan-in-CA** [comment]
Set GitHub to handle line ending on checkout:
https://help.github.com/articles/dealing-with-line-endings/

This should eliminate any future problems.
