### ISSUE TITLE
help

### ISSUE THREAD

**Issue by toshibochan** [Dan-in-CA/SIP#147]
i able to install to my raspberry pi, go to web and load correct but now asking me for password. what password it is? i need sip account or i need to set um on the python file?

thanks
toshi

**Comment by nathantsmith** [comment]
opendoor

**Comment by toshibochan** [comment]
thanks it works.
how i change password?

**Comment by toshibochan** [comment]
i find how thanks for help :-)

**Comment by toshibochan** [comment]
This need special hardware to work?

**Comment by toshibochan** [comment]
I can't just relays to use this?

**Comment by Dan-in-CA** [comment]
You can use a relay board.

Look here for information:
https://github.com/KanyonKris/relay_board/wiki
