### ISSUE TITLE
Missing translation for de_DE, more space for long german phrases

### ISSUE THREAD

**Issue by ED-from-AT** [Dan-in-CA/SIP#148]
First thanks for this great pieces of software!

Unfortunatly i miss the translation for "Water scaling" in Options.
German phrase for this could be "Wasser-Reduzierung".

The other thing is the space between description and options, checkboxes, etc.
In german (and maybe in other languages too) the descriptions ar longer then in english. So the text is maybe cutted on one or both ends.

Is it possible for you to enlarge the field for the description a little bit?

Kind regards
ED

**Comment by Dan-in-CA** [comment]
Hi Ed,

The spacing is something that needs work. I will look into it.
I have added your translation for "Water scaling". It looks like there are more text strings that are not in the DE translation. When changes are made to the software the translations don't always get updated.

Dan
