### ISSUE TITLE
Stations do not work after update

### ISSUE THREAD

**Issue by stephenyo** [Dan-in-CA/SIP#149]
After updating to 3.1.46 yesterday on my rPi model B (withOSPi board), my stations no longer work.  The log shows that each station is opening correctly, but there is no water coming out.  I'm fairly new to SIP- is there another log I can check?

**Comment by Dan-in-CA** [comment]
There is only one log file.
Have you tried running a station manually or from the Run Once page?

**Comment by stephenyo** [comment]
Yeah, I should have mentioned I tried both of those methods as well

**Comment by Dan-in-CA** [comment]
I updated an old version of OSPi here and it seem to be working properly.

A few questions to try and find a solution:
How did you do the updater? From the command line or using the system updater plugin?
Did you update from a version of OSPi or an older version of SIP? From you original post I'm guessing it was from OSPi.

If you use the command line I would suggest re-naming the OSPi directory then installing a fresh copy of SIP. See the instructions on the Wiki:
https://github.com/Dan-in-CA/SIP/wiki

Then you can copy your settings from the old OSPi directory.

Let me know if you need more details.

**Comment by stephenyo** [comment]
Thanks- I did it via command line.  I'll follow your directions and report back.

**Comment by Dan-in-CA** [comment]
The settings files are in the Data directory. If you copy the files
programs.json
sd.json
snames.json or snames.txt 
from the old data dir to the new one you should have all your settings intact.

Also you should follow the directions for starting the program automatically - the recommended method.
Be sure to disable the old ospi startup:
sudo update-rc.d ospi remove

and delete the ospi file in /etc/init.d/
sudo rm /etc/init.d/ospi

**Comment by stephenyo** [comment]
I went ahead and did a full wipe and reinstall of the Pi as well as SIP.
I'm good to go now - thanks!

**Comment by Dan-in-CA** [comment]
Cool. That seems like the best solution.
