### ISSUE TITLE
compatible with opensprinkler app?

### ISSUE THREAD

**Issue by bedros** [Dan-in-CA/SIP#150]
is this backend compatible with https://github.com/OpenSprinkler/OpenSprinkler-App

Thanks

**Comment by Dan-in-CA** [comment]
Yes, a user installed the app a few days ago and reported that it is working fine.

**Comment by bedros** [comment]
I doubt it would work with the app since the url used are totally different from yours 

https://opensprinkler.freshdesk.com/support/solutions/articles/5000678632-user-manual-firmware-2-1-6-current-
probably the user was running ospi firmware when testing the app

**Comment by Dan-in-CA** [comment]
SIP has a plugin (mobile_app plugin) that translates the URLs.

**Comment by bedros** [comment]
I'll give it a try, thanks for your help
