### ISSUE TITLE
Error when 'onbrd' not included when calling change_options

### ISSUE THREAD

**Issue by apogeecmb** [Dan-in-CA/SIP#153]
If 'onbrd' is not an option passed to change_options in webpages.py, the function call will result in an error.  I discovered this will testing out various web api calls.  When I tried to change options, the call would always result in an error result because I was not passing 'onbrd' as one of the options I wanted to change.  

I discovered this in an older version of the code, but looking at lines 176-180 in the current version of webpages.py on github, the unguarded reference to 'onbrd' still appears to be there.

**Comment by Dan-in-CA** [comment]
Thanks, I'll tak a look.

**Comment by Dan-in-CA** [comment]
Updated.
