### ISSUE TITLE
log

### ISSUE THREAD

**Issue by mrbeezer** [Dan-in-CA/SIP#154]
getting an internal server error when trying access the log, which is enabled,  Everything else seems ok.

**Comment by Dan-in-CA** [comment]
The log file may be corrupt. 
Try clicking the CLEAR LOG button at the bottom of the log page. That will create a new log file.

**Comment by begeles2000** [comment]
the SD card might be corrupt also, mine started failing this way and then
started to get worse

**Comment by mrbeezer** [comment]
Thanjs for responding but the screen I get is all white with the error
message in black at the top.
 
I renamed the SIP dir and reinstalled and it is working now..  Love this
program! Thanks!  Is there a plugin that aloows writing the date to a usb HD
or network drive?
 
Thanks again!
 

  _____

**Comment by Dan-in-CA** [comment]
Not a plugin but there are instructions on the SIP wiki that tell how to do it:
https://github.com/Dan-in-CA/SIP/wiki/flashdrive

**Comment by mrbeezer** [comment]
Thank you sir!  I have been in hi-tech a long time (40 yrs) and these new
innovations are wonderful.  Keep it up!
