### ISSUE TITLE
syntax error preventing watering

### ISSUE THREAD

**Issue by mihugo** [Dan-in-CA/SIP#163]
when a station runs the follow error is tossed:
NameError: global name 'strings' is not defined

caused by syntax error in   plugins/signaling_examples.py line 91: 
print "Some Stations has been scheduled: {}".format(strings(gv.rs))

a quick change is to just remove the strings()
print "Some Stations has been scheduled: {}".format(gv.rs)

**Comment by Pelado-Mat** [comment]
@mihugo,
                my mistake! just created  a pull request to @Dan-in-CA with the fix.

Regards
