### ISSUE TITLE
Negative numbers in Master On Delay crash SIP

### ISSUE THREAD

**Issue by Pelado-Mat** [Dan-in-CA/SIP#167]
The tool tips inform the user that the numbers mus be between 0 and +60, but it allows entering negative numbers in "Master on adjust"

If you, incorrecly, input a negative value SIP will crash when a program is run:
 File "/opt/SIP/sip.py", line 84, in timing_loop
 schedule_stations(p[7:7 + gv.sd['nbrd']])  # turns on gv.sd['bsy']
`
The user must be warned and we should not save an invalid configuration in sd.json

**Comment by Dan-in-CA** [comment]
Got it, Thanks. I'll work on fixing this. 
We really need a way to start the master before other stations start so the master can e.g. start a pump.

Foe now I will try to prevent the error.

**Comment by Dan-in-CA** [comment]
I pushed a fix.
Let me know if you still see any problem.
