### ISSUE TITLE
RunOnce Programs and concurrent stations, Master station OFF with stations running

### ISSUE THREAD

**Issue by Pelado-Mat** [Dan-in-CA/SIP#168]
Hi,
     I found a bug in the run once programs that I do not have the time yet to work on it, but I want to document.

If you run your stations concurrently and run a "RunOnce" program where one stations finish earlier than the rest, the master station is turned off with the first station, leaving all the other running without the master.

**Comment by Dan-in-CA** [comment]
Thank you, I will take a look.

**Comment by Dan-in-CA** [comment]
This was fixed on January 8 2017.
