### ISSUE TITLE
Does it support weather forecasts?

### ISSUE THREAD

**Issue by marksev1** [Dan-in-CA/SIP#171]
From Wunderground or Forecastio or something like that? So that it stops irrigation if rain is forecasted?
Or just via the rain sensor?

**Comment by Dan-in-CA** [comment]
There are 2 plugins that work with Weather Underground.

1. weather_adj  - will set a rain delay to prevent sprinklers from running if rain is predicted.
2. weather_level_adj - adjusts irrigation time depending on rain and prevents irrigation when low temperatures are predicted.

To install a plugin; open the Plugins menu > Manage Plugins > Browse More Plugins

**Comment by marksev1** [comment]
Cool, thanks.
