### ISSUE TITLE
Logging shows as Enabled when SIP starts up but is disabled

### ISSUE THREAD

**Issue by DaveSprague** [Dan-in-CA/SIP#180]
I noticed this as I was trying out some other code and noticed that when I did a Run Once program after starting up SIP, it didn't create a log even thought the Enable Logging option was Checked under the Options page.

Not certain but the issue might be that on line 62 in gv.py, the initial value of an empty string u"" rather than zero or one.  Other boolean options seem to be set to 0 or 1.

If you uncheck the Enable Logging Options and save that and then recheck the option and save it, then logging seems to work properly.  Even after a stop and start it continues to work correctly since the Enable Logging Option is saved in the sd.json options file.

**Comment by Dan-in-CA** [comment]
Fixed. 
You were correct about line 62 in gv.py needing to be 0.
Thanks.
