### ISSUE TITLE
Setting water level percentage ignores all programs

### ISSUE THREAD

**Issue by Tails86** [Dan-in-CA/SIP#183]
Running version 3.2.4

I don't have any of the "ignore" checkboxes checked in the Stations page. I set the water level to 66% and make a program. The program shows up on the calendar, but the program never starts when the time comes.

This issue goes away once I set the water level to "normal".

I disabled all plugins, but that does not help.

EDIT:
It works fine if I set the water level to 100% or more. It's when the water level is set to less than 100% that there is a problem.

**Comment by Dan-in-CA** [comment]
Thanks. I see the same problem here.
I will look for a fix and report back here.

**Comment by Dan-in-CA** [comment]
The problem with the water level percentage should be fixed now.
The problem was in sip.py line 74. The percentage value stored in the settings was not being converted to a float and as a result the calculation on that line always returned 0.
