### ISSUE TITLE
Where is STOP ALL STATIONS? 

### ISSUE THREAD

**Issue by elongo** [Dan-in-CA/SIP#191]
Hi Dan,

I am trying trigger a new function I wrote, once the user presses STOP ALL STATIONS on the home of SIP interface. However I haven't been able to find the code for stoping all stations. Could you point me in which script is the STOP ALL STATIONS CODE!! 

Many thanks!!

E

**Comment by Dan-in-CA** [comment]
That would be in helpers.py line 452

**Comment by elongo** [comment]
Thank you very much!!
Found it (in line 470). But all good. Thanks. ;)

**Comment by gdgeist** [comment]
Close?
