### ISSUE TITLE
Secure Remote Access

### ISSUE THREAD

**Issue by Pete-in-Perth** [Dan-in-CA/SIP#194]
Does anyone have advice on setting up secure remote access? I have tried the instructions in the link below but they don't seem to work as they were written for a previous version of ospi.
rayshobby.net/mediawiki/index.php?title=Secure_Remote_Access

**Comment by Pete-in-Perth** [comment]
Actually, I see now I am getting confused between different versions of ospi! You can close this one. Thanks.

**Comment by Dan-in-CA** [comment]
Actually I have been having good results using pivpn:
http://www.pivpn.io/

It allows for secure remote access and I use openvpn on my phone to access SIP securely from remote locations.
