### ISSUE TITLE
Weather Adjustment: Location issue

### ISSUE THREAD

**Issue by Dalmapalma** [Dan-in-CA/SIP#207]
Hi,

I just installed the weather ajdustment plugin. I added the city name 'Steinen'of my hometown as the ZIP Code or the coordinates were not working. But in Germany there are many cities called Steinen...How can I be sure that it is taken the right one?

**Comment by Dan-in-CA** [comment]
The weather plugins are not working properly due to changes weather underground.
See this issue:
https://github.com/Dan-in-CA/SIP/issues/205
Hopefully we will have an update before too long.

**Comment by Dan-in-CA** [comment]
The weather_level_adj plugin has been updated to use OpenWeathermap and location is by Latitude - Longitude (GPS) coordinates. That should avoid city name conflicts.
