### ISSUE TITLE
Default IP address is IPv4 only

### ISSUE THREAD

**Issue by hmoffatt** [Dan-in-CA/SIP#216]
The default listen IP address, 'htip' in the settings, is 0.0.0.0 (gv.py). This causes SIP only to listen for IPv4 connections and won't accept IPv6.

If this is changed to '::' then it will listen on both IPv4 and IPv6.

gv_reference.txt actually says '::' IS the default, but gv.py says otherwise.

I realise that an IPv6 sprinker system is truely a first world problem. But it's the only way I can connect to the controller inside my LAN from outside (where IPv4 is subject to NAT).

**Comment by Dan-in-CA** [comment]
Thanks for pointing that out.
I updated gv.py in the main branch.

Dan

**Comment by hmoffatt** [comment]
Thanks
