### ISSUE TITLE
Application Starts with IP/URL 0.0.0.0

### ISSUE THREAD

**Issue by konoichi** [Dan-in-CA/SIP#220]

**Comment by konoichi** [comment]
I did a fresh install on a new rasbian stretch light distro and ran into an issue after starting the application. It seems that SIP is not able to resolve the local IP address as SIP URL/IP is shown as 0.0.0.0:80.
I needed to edit the sd.json file and set the IP manually and I changed the port to 8080.
Now the application is running as it should but I hope someone can explain what whent wrong here.

**Comment by Dan-in-CA** [comment]
Not sure why you are seeing this.
There was a recent change to make the default IP address compatible with both IPv4 and IPv6. as described in issue #216:
https://github.com/Dan-in-CA/SIP/issues/216

You should be seeing something like http://:::80/ which is the new default.

**Comment by hemangjoshi37a** [comment]
how to change the default port 80 to anything else ?

**Comment by Dan-in-CA** [comment]
As the original poster mentioned you can edit the file SIP/data/sd.json. look for the line ""htp": 80, and chant the port there.
