### ISSUE TITLE
weather base water level isssues: no such file or directory..

### ISSUE THREAD

**Issue by aocana** [Dan-in-CA/SIP#225]
any idea why I have this error after try to configure weather adj.

> 
> Weather-base water level encountered error:
> Traceback (most recent call last):
>   File "/home/takezo/SIP/plugins/weather_level_adj.py", line 97, in run
>     today = today_info(self, options)
>   File "/home/takezo/SIP/plugins/weather_level_adj.py", line 313, in today_info
>     if name in os.listdir(path):
> OSError: [Errno 2] No such file or directory: './data/weather_level_history'

![Capture](https://user-images.githubusercontent.com/13902343/65144851-7e077900-da18-11e9-8723-76406d8311f8.JPG)

thanks for your support!

**Comment by Dan-in-CA** [comment]
The current version of the plugin has a bug.
It requires a folder named weather_level_history to be in the SIP/data/folder. The plugin is being updated and a new version should be ready in a few days.
See the issue on the SIP plugins repo:
https://github.com/Dan-in-CA/sip_plugins/issues/35

**Comment by aocana** [comment]
i look forward to the update!!!
thanks @Dan-in-CA  for your support!!!

**Comment by aocana** [comment]
where i can see when is delivery this new release?

thanks

**Comment by Dan-in-CA** [comment]
I will post an announcement on the SIP GitHub plugin forum:
Dan-in-CA/sip_plugins#35

and on the SIP forum:
https://nosack.com/sipforum/index.php

**Comment by aocana** [comment]
cool!

**Comment by Dan-in-CA** [comment]
OK. The weather_level_adj plugin update Is now available.
Click the "help" button on the plugin page to open the documentation page. It contains information about using geographic coordinates for your location.
