### ISSUE TITLE
passphrase login error with web.config._session.user in Py3_WIP branch

### ISSUE THREAD

**Issue by myspaghetti** [Dan-in-CA/SIP#226]
Hi! Thanks for SIP, it's the best irrigation software out there.

On the Py3_WIP branch, enabling passphrase calls `check_login`, which raises `AttributeError` because `web.config._session.user` is not yet set before a successful login.

Catching the exception in the following `except` allows the login to succeed or fail as intended, but the web server still redirects all requests to `/login`

**Comment by Dan-in-CA** [comment]
This took a while but I think it is fixed now.
You can update your SIP installation with:
git pull
from the SIP directory.

**Comment by myspaghetti** [comment]
Thanks! You made my day!
