### ISSUE TITLE
Module called future missing

### ISSUE THREAD

**Issue by Stifler6996** [Dan-in-CA/SIP#228]
Hi!
Rasbian buster (lite) and a fresh install (git clone) of sip gives this error:
```
Traceback (most recent call last):
  File "sip.py", line 6, in <module>
    from future import standard_library
ImportError: No module named future
```
Buster comes with Python 2.7.16 & Python 3.7.3 installed.
[future - http://python-future.org/](http://python-future.org/) Seems to be a Py2 to Py3 converter "helper"

My crappy resolution:
```
sudo apt install python-pip python3-pip
sudo pip install future
sudo pip3 install future
```
I believe that the 2.7 is the only one actually needed here.

Thanks!

**Comment by Dan-in-CA** [comment]
I believe this has been fixed.
If there is still a problem, please reopen.
