### ISSUE TITLE
Mobile app won’t connect 

### ISSUE THREAD

**Issue by garethjonesCN** [Dan-in-CA/SIP#233]
Hi. 

I rebuilt my system using the latest code after a hardware failure  Previously running code from 2017. Everything runs as great as ever but the mobile app will no longer connect.

**Comment by Dan-in-CA** [comment]
SIP v4 includes a new data file format and is no longer compatible with the OpenSprinker mobile app.
However. SIP can be accessed on mobile devices using a web browser. You can create a shortcut on the desktop for quick access.
The mobile app did not allow access to SIP plugins and as time went by the two platforms diverged more and more.

**Comment by garethjonesCN** [comment]
Thanks for the update, mobile access works great
