### ISSUE TITLE
Change SIP to other name

### ISSUE THREAD

**Issue by dioh** [Dan-in-CA/SIP#269]
I find that SIP is confusing as there is an associated technology called SIP (Sub irrigation planters).

**Comment by Dan-in-CA** [comment]
But Sub-Irrigated Planter is not software.

You can change the name of your SIP software installation on the Options page: 
Options > System > System name
The new name will be displayed in the header of each page.

**Comment by Noschvie** [comment]
SIP / Software : Session Initiation Protocol

**Comment by Dan-in-CA** [comment]
Yes. I am aware of that also.
The problem is that changing the name would effect every part of the project. Including this GitHub repository, plugins the discussion forum and an extensive rewrite of the software code itself.

It is not going to happen.

**Comment by dioh** [comment]
You are right, and I think the reason not to fix it is good. Sorry for bringing this up, I think this is a nice project!
