### ISSUE TITLE
Multiple master zone

### ISSUE THREAD

**Issue by garudaonekh** [Dan-in-CA/SIP#272]
hi, we need multiple master zone for our farm irrigation-at least two as there are several main water source

Is there anyway to get this done? Is it hard to customize the code as I can write Python code

**Comment by martinpihrt** [comment]
Hi, if it helps you, you can try OSPy (I'm sorry Dan), OSPy can do two main stations...
https://github.com/martinpihrt/OSPy
this is not about advertising, but about help
Martin

**Comment by Dan-in-CA** [comment]
Thanks for the post Martin,
It is always good to here from you. No problem for you to post your link.
Dan

**Comment by garudaonekh** [comment]
Thanks; Add another wire and diode to open a master relay is a workaround for me.
