### ISSUE TITLE
Watering time, main page stuck on Loading time

### ISSUE THREAD

**Issue by AlanTHumphreys** [Dan-in-CA/SIP#281]
Hi all, having issue with watering time on main page stuck on Loading... after a fresh install the screen looks ok, but as soon as i flip
enable as service (SIP 2 or SIP3) the main screen changes to Loading... The only way i can get it back is to do a full install again.

any ideas on why it could be happening.

Regards, Ala
<img width="1184" alt="Screen Shot 2021-12-27 at 9 02 41 am" src="https://user-images.githubusercontent.com/95603344/147421476-538984e4-ef59-4ef1-999c-87e97a357817.png">
n

**Comment by Dan-in-CA** [comment]
I am curious why the system on/off button is off. What happens of you change it to on?
Do you have any plugins installed? If so could you try disabling them.
If you start SIP from the command line do you see any error messages?

**Comment by AlanTHumphreys** [comment]
Hi Dan, since the issue non of the buttons worked except for running the programs. I was still running python2, have flipped
to python3 all is great now except for email module not loading even though its enabled under plugins.

No errors from command line, Only modules loaded are the default with Email and relay_board.

sudo python sip.py i can see the email module loaded ok. but running as service its a no show in the module list , currently running Debian latest version. first issue i have had in 5/6 years of use been flawless from get go.

<img width="1182" alt="1" src="https://user-images.githubusercontent.com/95603344/147514718-55199885-3756-4878-8edd-b352eca50422.png">
<img width="748" alt="2" src="https://user-images.githubusercontent.com/95603344/147514723-fce87ce7-82cc-42d4-a75b-333e622ad413.png">

**Comment by Dan-in-CA** [comment]
Thanks for the feedback. 
I'll take a look at the email plugin and get back to you.

**Comment by Dan-in-CA** [comment]
It looks like a lot has changed since the email_adj plugin was created. The Python3 email module will require change that are not easy to make both python 2 and 3 compatible. 

What I am planing to do is leave the email_adj plugin as is for use by anyone still running under Python2 and make an updated version for Python3 only. This may take a while to develop and test but it will be more secure.
Some of the newer plugins are Python3 only and I will be working on a Python3 only version of SIP.

Dan

**Comment by AlanTHumphreys** [comment]
Hey Dan, thanks for the update. shall wait for the mod.

Alan

**Comment by Dan-in-CA** [comment]
Alan,
I am considering a couple of ways to increase the number of SIP events that can be selected for email notifications.
What would you like to be able to monitor via email from SIP?

Dan

**Comment by noisymime** [comment]
FWIW I also had the same `LOADING...` issue after upgrading. Like Alan I was still on python 2, switching to python 3 resolved the issue.

**Comment by Dan-in-CA** [comment]
Thanks, It is fixed now for anyone wanting  run under Python2.
It had to do with the new named program feature and caused a hiccup in converting the name to JavaScript format.

Dan

**Comment by AlanTHumphreys** [comment]
Hi Dan, 
the main event for me was, notification the program ran. being in an area where they are always cleaning the recycled water
pipes, email notification on pressure drop would be good, or SIP would pause till specified percentage is reached.

Alan

**Comment by Dan-in-CA** [comment]
@AlanTHumphreys ,
The new Python3 email plugin named "sip_email" has now been posted to the SIP plugins repo.
Let me know if it does what you need or if there are any other notifications you would like to see.  
Dan

**Comment by AlanTHumphreys** [comment]
Excellent Dan, thank you will try it out

Alan
