### ISSUE TITLE
Webservice not starting if IPv6 disabled on Raspberry Pi

### ISSUE THREAD

**Issue by ED-from-AT** [Dan-in-CA/SIP#299]
If i disable IPv6 (added the parameter ipv6.disable=1 in /boot/cmdline.txt) on a Raspberry Pi the Webservice doesn't start.

**Comment by Dan-in-CA** [comment]
That looks like it could be a problem with the web.py framework SIP is built on:
https://github.com/webpy/webpy

or the cheroot server software SIP uses:
https://github.com/cherrypy/cheroot

**Comment by Dan-in-CA** [comment]
I tested adding ipv6.disable=1 in /boot/cmdline.txt but did not see any problem on re-starting SIP.
Dan
