### ISSUE TITLE
Wrong log date

### ISSUE THREAD

**Issue by ctosae** [Dan-in-CA/SIP#309]
After the last update the log writes the wrong day

```
{"program": "SP", "station": 2, "duration": "32:33", "start": "23:32:33", "date": "2023-09-07"}
{"program": "SP", "station": 1, "duration": "32:33", "start": "23:00:00", "date": "2023-09-06"}
{"program": "SP", "station": 2, "duration": "32:30", "start": "23:32:30", "date": "2023-09-03"}
{"program": "SP", "station": 1, "duration": "32:30", "start": "23:00:00", "date": "2023-09-03"}
```

Line 1 and 2 are with the new version
Line 3 and 4 are with the old version.

The program start at "23:32:33" (after "23:00:00" +"32:33") so the date is still "2023-09-06" and not "2023-09-07" (when it ends)

**Comment by Dan-in-CA** [comment]
Thank you for reporting this.

I will test here and check the code then post here when I find the problem.
Dan

**Comment by ctosae** [comment]
Thank you!

**Comment by Dan-in-CA** [comment]
If station 2 starts at "23:32:33" (less than half an hour before midnight) and runs for  32:33" (a little more than half an hour) it would end the next day (after midnight).

The new version of SIP allows for programs to run past midnight.

Dan

**Comment by ctosae** [comment]
Also the old program allows to run past midnight (see old log)

The wrong in this version is the (start) time in log.

checking logs it's not clear to understand if it’s the program of the day or of the day before.
Also because the "original" program (station1 + station2) starts at 23.00 of the previous day in log 

I hope you can fix it or I can't understand easly when stations run.

Thanks

**Comment by Dan-in-CA** [comment]
OK. 
I see what you are saying. The date field should show when the program started.
I will work on fixing that.

Dan

**Comment by ctosae** [comment]
Yes, exactly.

Thank you so much Dan

**Comment by jonathan-marsh** [comment]
I noticed this last week and developed a fix, but I haven’t tested it thoroughly yet, or verified that the apparent orphan code I deleted is truly orphaned:

 

It also looks like it affect “node red” programs but I have no idea what that is 😉.  This is not a great fix – the origin of the problem should be that gv.lrun always has a fully accurate time and date stamp for the start time.  But at least it might point to the location of the problem.  

 

-Jonathan

**Comment by jonathan-marsh** [comment]
Github stripped the link?  Not so good at git yet.  Here’s a screenshot:

 



 

             

 

From: ***@***.*** ***@***.***> 
Sent: Monday, September 11, 2023 1:56 PM
To: 'Dan-in-CA/SIP' ***@***.***>; 'Dan-in-CA/SIP' ***@***.***>
Cc: 'Subscribed' ***@***.***>
Subject: RE: [Dan-in-CA/SIP] Wrong log date (Issue #309)

 

I noticed this last week and developed a fix, but I haven’t tested it thoroughly yet, or verified that the apparent orphan code I deleted is truly orphaned:

 

It also looks like it affect “node red” programs but I have no idea what that is 😉.  This is not a great fix – the origin of the problem should be that gv.lrun always has a fully accurate time and date stamp for the start time.  But at least it might point to the location of the problem.  

 

-Jonathan

**Comment by Dan-in-CA** [comment]
I just pushed an update (version 5.0.18) that I believe fixes 3 time related bugs.

1. the log date bug
2. the program duration bug
3. a bug that would raise an error if a duration for a program was less than 30 seconds. 
I often use 5 or 10 second durations for testing.

Dan

**Comment by ctosae** [comment]
> I just pushed an update (version 5.0.18) that I believe fixes 3 time related bugs.

Let me try.... and offer you a pizza and beer in the meantime. Is this still valid? ;-)
https://www.paypal.me/Dan803393

**Comment by ctosae** [comment]
Working!
