### ISSUE TITLE
Station running (00:00)

### ISSUE THREAD

**Issue by ctosae** [Dan-in-CA/SIP#319]
This morning I found this state: 

![image](https://github.com/Dan-in-CA/SIP/assets/75297085/daafc2b3-58ec-47fc-b303-f70e716c8417)

It was 9:30am and the scheduling was for 3:30am
I had to push the button “`STOP ALL STATIONS`”

As you can see my plugins set "Total adjustment 0%", 
so the **station should not start**...

@Dan-in-CA could it depend on this https://github.com/Dan-in-CA/SIP/issues/309#issuecomment-1715843721 ?
_a bug that would raise an error if a duration for a program was less than 30 seconds._

Maybe jobs less than 5sec could be skipped

Thanks

**Comment by Dan-in-CA** [comment]
I did a quick test with a plugin adjustment set to 0% and the stations did not start.
However the home page did show the station scheduled to run for (00.00)  but not running.

That is a bug.

Dan

**Comment by ctosae** [comment]
Yes I can confirm that is not running, only web page like your description.
It has never happened before... often my plugins set to 0%.
I think it's introduced with that change

**Comment by ctosae** [comment]
Thank you! I will try it

**Comment by Dan-in-CA** [comment]
An unexpected benefit of the new node-red SIP extension helped find the problem.
https://en.wikipedia.org/wiki/Node-RED

A simple node-red flow can read SIP variables while the program is running.
![program-num](https://github.com/Dan-in-CA/SIP/assets/4706639/b1f9989e-4f70-4e63-b1c6-56bcb857fd18)
It showed that in the gv.rs (run schedule) var station 2 had a station number but not a duration other  value.

**Comment by ctosae** [comment]
Working fix! Thanks @Dan-in-CA 

**Node-Red**: I have heard high praises from those primarily engaged in developing IoT devices.
The implementation in SIP is excellent; I'm extremely pleased with this project 🥇 

It’s a pity that our summer and irrigation period only lasts from May to the end of September approximately.
Soon, it will have to hibernate for a while...
