### ISSUE TITLE
Run once broken

### ISSUE THREAD

**Issue by Kali-** [Dan-in-CA/SIP#324]
I have issue with run once, the issue happen at the end of the run, and this is the log:

Oct 30 10:08:38 orangepipc2 sip[1127131]: Exception in thread Thread-2 (timing_loop):
Oct 30 10:08:38 orangepipc2 sip[1127131]: Traceback (most recent call last):
Oct 30 10:08:38 orangepipc2 sip[1127131]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Oct 30 10:08:38 orangepipc2 sip[1127131]:     self.run()
Oct 30 10:08:38 orangepipc2 sip[1127131]:   File "/usr/lib/python3.10/threading.py", line 953, in run
Oct 30 10:08:38 orangepipc2 sip[1127131]:     self._target(*self._args, **self._kwargs)
Oct 30 10:08:38 orangepipc2 sip[1127131]:   File "/opt/sip/sip.py", line 139, in timing_loop
Oct 30 10:08:38 orangepipc2 sip[1127131]:     log_run()
Oct 30 10:08:38 orangepipc2 sip[1127131]:   File "/opt/sip/helpers.py", line 352, in log_run
Oct 30 10:08:38 orangepipc2 sip[1127131]:     pdur = gv.pd[pid]["duration_sec"][gv.lrun[0]]
Oct 30 10:08:38 orangepipc2 sip[1127131]: IndexError: list index out of range

**Comment by Dan-in-CA** [comment]
Yes, I was already working on that bug. Rev 
5.0.53 should be working properly.
