### ISSUE TITLE
Run-once wrong email report 

### ISSUE THREAD

**Issue by Kali-** [Dan-in-CA/SIP#333]
Just reporting a small cosmetics issue about the email report of Run-once

"
The Run-once program ended at 17:16.

Stations logged in this program:
Date            StartTime       Duration        Station
"

it always report 17:16 no matter what time it end and no details

**Comment by Dan-in-CA** [comment]
I see the problem.
Will post her when it is fixed,

**Comment by Dan-in-CA** [comment]
It should be fixed now.
Sorry for the delay.

**Comment by Kali-** [comment]
no rush, was just cosmetics
i really apreciate your work
