### ISSUE TITLE
Interval program works fine, but timeline is wrong

### ISSUE THREAD

**Issue by Kali-** [Dan-in-CA/SIP#339]
i have set 2 programs with 2 day interval one start at 0 and one start at 1 and they works as expected

but the timeline in the homepage is wrong as the order is reversed
its a bit confusing, as today was performed prog 2 and tomorrow it show prog 2 again (and was the same yesterday with prog 1)

**Comment by ctosae** [comment]
Could you check if it's the same: https://github.com/Dan-in-CA/SIP/issues/318 ?

This is the last update of the issue: https://github.com/Dan-in-CA/SIP/issues/318#issuecomment-2154341544

**Comment by Kali-** [comment]
not sure is the same issue, i have 2 program and they run alternately every day

this i my 2 programs:
<img width="1029" alt="Screenshot 2024-06-21 at 19 44 03" src="https://github.com/Dan-in-CA/SIP/assets/296919/3770df65-e79a-4c90-ba70-6e59bece43a7">
<img width="1029" alt="Screenshot 2024-06-21 at 19 43 41" src="https://github.com/Dan-in-CA/SIP/assets/296919/40c13e3d-0b7f-43f6-83dc-c66d9f7c752f">

this is the timeline
yesterday
<img width="804" alt="Screenshot 2024-06-21 at 19 38 16" src="https://github.com/Dan-in-CA/SIP/assets/296919/170a303a-50ac-4f14-9f17-a64905fc09ba">

today
<img width="808" alt="Screenshot 2024-06-21 at 19 38 27" src="https://github.com/Dan-in-CA/SIP/assets/296919/b4490490-bc7a-4faa-a638-9a4bb35c0f53">

tomorrow
<img width="806" alt="Screenshot 2024-06-21 at 19 38 43" src="https://github.com/Dan-in-CA/SIP/assets/296919/c46f8631-4b97-453e-95f7-b62ee0a4c94b">

the day after tomorrow
<img width="808" alt="Screenshot 2024-06-21 at 19 38 53" src="https://github.com/Dan-in-CA/SIP/assets/296919/58e495e0-47d0-4877-bdd8-cbec93e40a32">

as shown, the timeline of tomorrow says it will run the same program as today, but tomorrow SIP will run the other one
so in the past the timeline is correct, in the future they are inverted

**Comment by jonathan-marsh** [comment]
While I haven't been able to reproduce this exactly, I just created a pull request for a related bug that could be causing this as well.  After the request gets accepted, please update and retest and if it still occurs send me additional information - e.g. timezone of the system.

**Comment by ctosae** [comment]
Thank you @jonathan-marsh for your support.
I tested it manually, but in my case it didn't solve the problem.
This is the local time: `/etc/localtime -> /usr/share/zoneinfo/Europe/Rome`
Note. I'm using it with docker.. can you try this setup? It's easy to reproduce with all steps here #338 
When it is accepted we await feedback from @Kali- as well

**Comment by Kali-** [comment]
no, still not working properly
also for the 1st time the program crashed

Jul 15 14:00:21 orangepipc2 sip[548924]: Traceback (most recent call last):
Jul 15 14:00:21 orangepipc2 sip[548924]:   File "/opt/sip/web/application.py", line 288, in process
Jul 15 14:00:21 orangepipc2 sip[548924]:     return p(lambda: process(processors))
Jul 15 14:00:21 orangepipc2 sip[548924]:   File "/opt/sip/web/application.py", line 699, in processor
Jul 15 14:00:21 orangepipc2 sip[548924]:     h()
Jul 15 14:00:21 orangepipc2 sip[548924]:   File "/opt/sip/web/application.py", line 805, in __call__
Jul 15 14:00:21 orangepipc2 sip[548924]:     self.check(mod)
Jul 15 14:00:21 orangepipc2 sip[548924]:   File "/opt/sip/web/application.py", line 826, in check
Jul 15 14:00:21 orangepipc2 sip[548924]:     reload(mod)
Jul 15 14:00:21 orangepipc2 sip[548924]:   File "/usr/lib/python3.10/importlib/__init__.py", line 169, in reload
Jul 15 14:00:21 orangepipc2 sip[548924]:     _bootstrap._exec(spec, module)
Jul 15 14:00:21 orangepipc2 sip[548924]:   File "<frozen importlib._bootstrap>", line 601, in _exec
Jul 15 14:00:21 orangepipc2 sip[548924]:   File "<frozen importlib._bootstrap>", line 174, in __exit__
Jul 15 14:00:21 orangepipc2 sip[548924]:   File "<frozen importlib._bootstrap>", line 126, in release
Jul 15 14:00:21 orangepipc2 sip[548924]: AttributeError: 'NoneType' object has no attribute 'get_ident'
Jul 15 14:00:21 orangepipc2 sip[548924]: ::ffff:94.156.10.163:57058 - - [15/Jul/2024 14:00:21] "HTTP/1.1 POST /goform/set_LimitClient_cfg" - 500 Internal Server Error

**Comment by ctosae** [comment]
@Kali- problem solved. Try updating to:
```
SIP version: 	5.1.76
SIP date: 	2024-08-24 
```

**Comment by Kali-** [comment]
confirmed!
